# =========================================================================
# PROYECTO FINAL: Módulo de Productos (taller-products)
# FACULTAD DE INFORMÁTICA - UAQ
# =========================================================================

service: taller-products
frameworkVersion: "4"

# Variables personalizadas del proyecto
custom:
  productsTableName: ${self:service}-${self:provider.stage}-products

# Configuración del proveedor AWS, incluyendo runtime, región, variables de entorno y configuración de API Gateway.
provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}
    CORS_ORIGIN: ${file(./config/config-${self:provider.stage}.json):CORS_ORIGIN}
    PRODUCTS_TABLE: ${self:custom.productsTableName}

  apiGateway:
    restApiId: ${cf:taller-gateway-${self:provider.stage}.MainRestApiId}
    restApiRootResourceId: ${cf:taller-gateway-${self:provider.stage}.MainRestApiRootResourceId}
      
  iamRoleStatements:
    # Permisos de auditoría y logs en CloudWatch
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    # Permisos de lectura/escritura sobre la tabla de Productos y sus Índices (GSI)
    - Effect: Allow
      Action: 
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - Fn::GetAtt: [ProductsTable, Arn]
        - Fn::Join:
            - "/"
            - - Fn::GetAtt: [ProductsTable, Arn]
              - "index/*"

# =========================================================================
# DECLARACIÓN DE FUNCIONES LAMBDA / ENDPOINTS
# =========================================================================
functions:
  # Lambda para crear un producto, que se activa con solicitudes POST a la ruta /products, y está protegida por un Authorizer personalizado que valida tokens JWT para asegurar que solo usuarios autenticados puedan crear productos.
  createProduct: 
    handler: src/handlers/createProducts.createProducts
    name: taller-${self:provider.stage}-Products-Create
    events:
      - http:
          method: post
          path: /products
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

  # Lambda para obtener un producto por su ID, que se activa con solicitudes GET a la ruta /products/{id}, y está protegida por un Authorizer personalizado que valida tokens JWT para asegurar que solo usuarios autenticados puedan acceder a los detalles de un producto específico.
  getProduct: 
    handler: src/handlers/getProduct.getProduct
    name: taller-${self:provider.stage}-Products-Get
    events:
      - http:
          method: get
          path: /products/{id}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token

  # Lambda para listar todos los productos disponibles, que se activa con solicitudes GET a la ruta /products, y está abierta al público sin necesidad de autenticación, permitiendo que cualquier usuario pueda ver el catálogo completo de productos.
  listAllProduct: 
      handler: src/handlers/listAllProducts.listAllProducts
      name: taller-${self:provider.stage}-Products-ListALLProducts
      events:
        - http:
            method: get
            path: /products
            cors:
              origin: "*"
              headers: 
                  - Content-Type
                  - Authorization
                  - X-Api-Key
                  - X-Amz-Date
                  - X-Amz-Security-Token

  # Lambda para listar productos por vendedor, que se activa con solicitudes GET a la ruta /products/users/{sellerId}, y está protegida por un Authorizer personalizado que valida tokens JWT para asegurar que solo usuarios autenticados puedan acceder a los productos de un vendedor específico.
  listProductsBySeller: 
    handler: src/handlers/listProductsBySeller.listProductsBySeller
    name: taller-${self:provider.stage}-Products-ListBySeller
    events:
      - http:
          method: get
          path: /products/users/{sellerId}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token

# Cuando algún usuario compra un producto o varios productos
  updateStock: 
    handler: src/handlers/updateStock.updateStock
    name: taller-${self:provider.stage}-Products-UpdateStock
    events:
      - http:
          method: patch
          path: /products/{id}/stock
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token

  # Lambda para actualizar un producto, que se activa con solicitudes PUT a la ruta /products/{id}, y está protegida por un Authorizer personalizado que valida tokens JWT para asegurar que solo usuarios autenticados puedan modificar los detalles de un producto específico.
  updateProduct: 
    handler: src/handlers/updateProduct.updateProduct
    name: taller-${self:provider.stage}-Products-Update
    events:
      - http:
          method: put
          path: /products/{id}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

  # Lambda para eliminar un producto, que se activa con solicitudes DELETE a la ruta /products/{id}, y está protegida por un Authorizer personalizado que valida tokens JWT para asegurar que solo usuarios autenticados puedan eliminar un producto específico.
  deleteProduct: 
    handler: src/handlers/deleteProduct.deleteProduct
    name: taller-${self:provider.stage}-Products-Delete
    events:
      - http:
          method: delete
          path: /products/{id}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

# =========================================================================
# RECURSOS DE INFRAESTRUCTURA (CloudFormation / NoSQL Tables)
# =========================================================================
resources: 
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.productsTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
          - AttributeName: sellerId
            AttributeType: S
        
        KeySchema: 
          - AttributeName: productId
            KeyType: HASH
        
        GlobalSecondaryIndexes:
          - IndexName: sellerIndex
            KeySchema:
              - AttributeName: sellerId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
              
