# Desarrollado por: Gabriel Campos - 325844
service: taller-gateway
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}
    JWT_SECRET: ${ssm:/taller/${self:provider.stage}/jwt-secret}
    CORS_ORIGIN: ${file(./config/config-${self:provider.stage}.json):CORS_ORIGIN}

  apiGateway:
    usagePlan:
      quota:
        limit: 10000
        period: MONTH
      throttle:
        burstLimit: 20
        rateLimit: 10
    apiKeys:
      - ${self:provider.stage}-AmazonLite-DefaultKey

  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  ping:
    handler: src/handlers/ping.ping
    name: taller-${self:provider.stage}-Gateway-Ping
    events:
      - http:
          method: get
          path: /gateway/ping
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Api-Key
              - X-Amz-Date
              - X-Amz-Security-Token
  authorizer:
    handler: src/handlers/authorizer.authorizer
    name: taller-${self:provider.stage}-Authorizer

resources:
  Resources:
  
    MainAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: taller-${self:provider.stage}-jwt-authorizer
        Type: TOKEN
        IdentitySource: method.request.header.Authorization
        RestApiId: 
          Ref: ApiGatewayRestApi
        AuthorizerUri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerLambdaFunction.Arn}/invocations

    AuthorizerInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt: [ AuthorizerLambdaFunction, Arn ]
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com
        SourceArn:
          Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/authorizers/*

    GatewayResponseUnauthorized:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseType: UNAUTHORIZED
        StatusCode: "401"
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type, Authorization, X-Api-Key, X-Amz-Date, X-Amz-Security-Token'"

    GatewayResponseAccessDenied:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseType: ACCESS_DENIED
        StatusCode: "403"
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type, Authorization, X-Api-Key, X-Amz-Date, X-Amz-Security-Token'"

    GatewayResponseDefault4xx:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseType: DEFAULT_4XX
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type, Authorization, X-Api-Key, X-Amz-Date, X-Amz-Security-Token'"

    GatewayResponseDefault5xx:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseType: DEFAULT_5XX
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type, Authorization, X-Api-Key, X-Amz-Date, X-Amz-Security-Token'"

  Outputs:
    MainRestApiId:
      Value: { Ref: ApiGatewayRestApi }
      Export: 
        Name: ${self:service}-${self:provider.stage}-MainRestApiId 

    MainRestApiRootResourceId:
      Value:
        Fn::GetAtt: [ApiGatewayRestApi, RootResourceId]
      Export: 
        Name: ${self:service}-${self:provider.stage}-MainRestApiRootResourceId

    MainAuthorizerId:
      Value: { Ref: MainAuthorizer }
      Export: 
        Name: ${self:service}-${self:provider.stage}-AuthorizerId 