# =========================================================================
# PROYECTO FINAL: Módulo de Usuarios (taller-users)
# FACULTAD DE INFORMÁTICA - UAQ
# =========================================================================

service: taller-users
frameworkVersion: "4"

# Variables personalizadas del proyecto
custom:
  usersTableName: ${self:service}-${self:provider.stage}-users
  refreshTokensTableName: ${self:service}-${self:provider.stage}-refresh-tokens

# Configuración del proveedor AWS, incluyendo runtime, región, variables de entorno y configuración de API Gateway.
provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}
    JWT_SECRET: ${ssm:/taller/${self:provider.stage}/jwt-secret, 'local-dev-secret'}
    JWT_REFRESH_SECRET: ${ssm:/taller/${self:provider.stage}/jwt-refresh-secret, 'local-dev-refresh-secret'}
    CORS_ORIGIN: ${file(./config/config-${self:provider.stage}.json):CORS_ORIGIN}
    USERS_TABLE: ${self:custom.usersTableName}
    REFRESH_TOKEN_TABLE: ${self:custom.refreshTokensTableName}
    

  apiGateway:
    restApiId: ${cf:taller-gateway-${self:provider.stage}.MainRestApiId}
    restApiRootResourceId: ${cf:taller-gateway-${self:provider.stage}.MainRestApiRootResourceId}
      
  iamRoleStatements:
    # Permisos de auditoría y logs en CloudWatch
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    # Permisos de lectura/escritura sobre la tabla de Productos y sus Índices (GSI)
    - Effect: Allow
      Action: 
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - Fn::GetAtt: [UsersTable, Arn]
        - Fn::Join:
            - "/"
            - - Fn::GetAtt: [UsersTable, Arn]
              - "index/*"
        - Fn::GetAtt: [RefreshTokensTable, Arn]

# =========================================================================
# DECLARACIÓN DE FUNCIONES LAMBDA / ENDPOINTS
# =========================================================================
functions:
  # Lambda para registrar un nuevo usuario, que se activa con solicitudes POST a la ruta /users/register, y permite a los usuarios crear una cuenta proporcionando su información básica (nombre, correo electrónico, contraseña), con validaciones para asegurar que el correo no esté ya registrado y que la contraseña cumpla con ciertos criterios de seguridad.
  register: 
    handler: src/handlers/register.register
    name: taller-${self:provider.stage}-Users-Register
    events:
      - http:
          method: post
          path: /users/register
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token

  # Lambda para iniciar sesión, que se activa con solicitudes POST a la ruta /users/login, y permite a los usuarios autenticarse proporcionando su correo electrónico y contraseña, validando las credenciales contra la base de datos, y generando un token JWT de acceso junto con un token de refresco para mantener la sesión activa.
  login:
    handler: src/handlers/login.login
    name: taller-${self:provider.stage}-Users-Login
    events:
      - http:
          method: post
          path: /users/login
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token

  # Lambda para refrescar tokens, que se activa con solicitudes POST a la ruta /users/refresh-token, y permite a los usuarios obtener un nuevo token JWT de acceso utilizando un token de refresco válido, asegurando que el token de refresco esté registrado en la base de datos y no haya expirado antes de emitir un nuevo token de acceso.
  getUser:
    handler: src/handlers/getUser.getUser
    name: taller-${self:provider.stage}-Users-GetUser
    events:
      - http:
          method: get
          path: /users/{id}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

  # Lambda para actualizar la información de un usuario, que se activa con solicitudes PUT a la ruta /users/{id}, y permite a los usuarios autenticados actualizar su información personal (nombre, correo electrónico, contraseña), con validaciones para asegurar que solo el usuario propietario de la cuenta pueda realizar cambios, y que los datos actualizados cumplan con los criterios de seguridad y formato.
  updateUser:
    handler: src/handlers/updateUser.updateUser
    name: taller-${self:provider.stage}-Users-Update
    events:
      - http:
          method: put
          path: /users/{id}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

  # Lambda para eliminar un usuario, que se activa con solicitudes DELETE a la ruta /users/{id}, y permite a los usuarios autenticados eliminar su cuenta, con validaciones para asegurar que solo el usuario propietario de la cuenta pueda realizar esta acción.
  deleteUser:
    handler: src/handlers/deleteUser.deleteUser
    name: taller-${self:provider.stage}-Users-Delete
    events:
      - http:
          method: delete
          path: /users/{id}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

# =========================================================================
# RECURSOS DE INFRAESTRUCTURA (CloudFormation / NoSQL Tables)
# =========================================================================
resources: 
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        
        KeySchema: 
          - AttributeName: userId
            KeyType: HASH
        
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
              
    RefreshTokensTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-refresh-tokens
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S

        KeySchema: 
          - AttributeName: token
            KeyType: HASH
        # Tiempo de vida del token
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true
      


        
    

