# Desarrollado por: Gabriel Campos - 325844
service: taller-orders
frameworkVersion: "4"

custom:
  ordersTableName: ${self:service}-${self:provider.stage}-orders

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}
    CORS_ORIGIN: ${file(./config/config-${self:provider.stage}.json):CORS_ORIGIN}
    ORDERS_TABLE: ${self:custom.ordersTableName}

  apiGateway:
    restApiId: ${cf:taller-gateway-${self:provider.stage}.MainRestApiId}
    restApiRootResourceId: ${cf:taller-gateway-${self:provider.stage}.MainRestApiRootResourceId}
      
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action: 
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - Fn::GetAtt: [OrdersTable, Arn]
        - Fn::Join:
            - "/"
            - - Fn::GetAtt: [OrdersTable, Arn]
              - "index/*"
    - Effect: Allow
      Action: 
        - lambda:InvokeFunction
      Resource:
        - Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:taller-${self:provider.stage}-Products-*"

functions:
  createOrders: 
    handler: src/handlers/createOrders.createOrders
    name: taller-${self:provider.stage}-Orders-Create
    events:
      - http:
          method: post
          path: /orders/create
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

  getOrder: 
    handler: src/handlers/getOrder.getOrder
    name: taller-${self:provider.stage}-Orders-GetOrder
    events:
      - http:
          method: get
          path: /orders/{id}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

  listOrdersbyUserId: 
    handler: src/handlers/listOrdersbyUserId.listOrdersbyUserId
    name: taller-${self:provider.stage}-Orders-ListByUser
    events:
      - http:
          method: get
          path: /orders/user/{userId}
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

  cancelOrder: 
    handler: src/handlers/cancelOrder.cancelOrder
    name: taller-${self:provider.stage}-Orders-Cancel
    events:
      - http:
          method: post
          path: /orders/{id}/cancel
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}

  confirmOrder: 
    handler: src/handlers/confirmOrder.confirmOrder
    name: taller-${self:provider.stage}-Orders-Confirm
    events:
      - http:
          method: post
          path: /orders/{id}/confirm
          cors:
            origin: "*"
            headers: 
                - Content-Type
                - Authorization
                - X-Api-Key
                - X-Amz-Date
                - X-Amz-Security-Token
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:taller-gateway-${self:provider.stage}.MainAuthorizerId}



resources: 
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ordersTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        
        KeySchema: 
          - AttributeName: orderId
            KeyType: HASH
        
        GlobalSecondaryIndexes:
          - IndexName: UserOrderIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
              
